### ISSUE TITLE
Hide/Timeout doesn't fully hide twitt

### ISSUE THREAD

**Issue by noLogica** [splitscreen/ss-twitter#12]
Hi guys, I'm a newbie at programming, its not my field so don't be to harsh on me xD 

I've already tried a few clean installations of the bundle and same thing keeps happening:
- When using hide or a custom timeout the tweet on the exit animation leaves a bit of the body behind.
- After that If I refresh the page on the OBS Studio, it goes away. If I dont refresh the page it stays there, even when I grab another URL.

Any idea what can it be?
(example)

![problem](https://cloud.githubusercontent.com/assets/17803648/13725448/039928d0-e89a-11e5-915b-0412e5344eae.gif)

And Thanks for making this, its really awesome.

**Comment by techguydave** [comment]
That's super odd. I haven't come across that issue at all.

What's the resolution you added the page as?

**Comment by noLogica** [comment]
1920x1080
I've tested it on the regular OBS and also did the same thing :/

**Comment by techguydave** [comment]
I've got very little free time this week to work on things, but I'll try to get around to it.

Does it work in regular Chrome?
