### ISSUE TITLE
{Suggestion} Migrate to SupportClass/lfg-sounds

### ISSUE THREAD

**Issue by coolacid** [splitscreen/ss-twitter#5]
A suggestion would be to migrate sounds to SupportClass/lfg-sounds

**Comment by techguydave** [comment]
That looks pretty cool. I think it'd be a great addition. Is it safe to assume that most installs of NodeCG meet the 0.7.2 requirement?

**Comment by coolacid** [comment]
Any 0.7 should upgrade as required. I see no problem with it ;)

**Comment by techguydave** [comment]
Sounds good! Didn't want to alienate any potential users. I should have some time to attack this tomorrow evening.

**Comment by techguydave** [comment]
There's a PR open for branch [lfg-sounds](https://github.com/splitscreen/ss-twitter/tree/lfg-sounds), if you'd like to take a look and let me know if everything works as expected.
